title: Page
pages: true
files: true
fields:
  tabContent: tabContent
  title: title
  menu_title: menu_title
  sections: sections
  accordion: accordion
  tabSEO: tabSEO
  title_tag: title_tag
  description: description
  keywords: keywords